name: omni_track_core
description: >- 
  Omni Track Core is the foundation of Omni Track, providing interfaces and abstractions 
  for custom log creation and integration with drivers like omni_track_crashlytics and omni_track_sentry.
version: 1.0.0-dev.0
homepage: https://github.com/academiadoflutter/omni-track/packages/omni-track-core
repository: https://github.com/academiadoflutter/omni-track/packages/omni-track-core
issue_tracker: https://github.com/academiadoflutter/omni-track/issues
resolution: workspace


environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
