name: omni_track_crashlytics
description: >- 
  Omni Track Crashlytics is a log driver for Omni Track, integrating with Firebase Crashlytics 
  for automatic error tracking and real-time diagnostics with minimal setup.
version: 1.0.0-dev.0
homepage: https://github.com/academiadoflutter/omni-track/packages/omni-track-crashlytics
repository: https://github.com/academiadoflutter/omni-track/packages/omni-track-crashlytics
issue_tracker: https://github.com/academiadoflutter/omni-track/issues
resolution: workspace


environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
